name: Deploy Terraform to Google Cloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}

    steps:
    - name: Checkout Terraform repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.5

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.SA_EMAIL }}
        create_credentials_file: true
        export_environment_variables: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Verify Terraform files
      run: |
        ls -la infra
        pwd

    - name: Print Environment Variables
      run: printenv | grep TF_

    - name: Initialize Terraform
      run: terraform init --upgrade
      working-directory: ./infra

    - name: Select Terraform Workspace
      run: terraform workspace select ${{ env.TF_WORKSPACE }} || terraform workspace new ${{ env.TF_WORKSPACE }}
      working-directory: ./infra

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan
      working-directory: ./infra

    - name: Apply Terraform changes
      run: terraform apply -auto-approve tfplan
      working-directory: ./infra